# Generated by Django 4.1.5 on 2023-01-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='allow_comments',
            field=models.BooleanField(default=True, help_text='Whether to allow the comments in post or not'),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, help_text='Optional', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='stick_at_top',
            field=models.BooleanField(default=False, verbose_name='Stick to the Top of the Blog'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
