# Generated by Django 4.1.5 on 2023-01-15 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heading', to='core_app.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('heading', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heading', to='core_app.heading')),
            ],
        ),
    ]
